set(SENSEI_BACKEND $ENV{SENSEI_BACKEND})
set(SENSEI_BRANCH $ENV{SENSEI_BRANCH})
set(CTEST_SITE "sensei-ascent-sc19.dhcp.lbl.gov")
set(CTEST_BUILD_NAME "sensei-${SENSEI_BACKEND}-${SENSEI_BRANCH}")
set(CTEST_DASHBOARD_ROOT "$ENV{DASHROOT}")
set(INITIAL_CACHE
"CMAKE_BUILD_TYPE=Debug
BUILD_TESTING=ON
ENABLE_SENSEI=ON
ENABLE_VTK_IO=ON
ENABLE_VTK_MPI=ON
ENABLE_PYTHON=ON
ENABLE_ADIOS1=ON
ENABLE_ADIOS2=OFF
ENABLE_HDF5=ON
HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi
VTK_DIR=/home/sensei/sensei_insitu/software/vtk/8.2.0/lib/cmake/vtk-8.2
ADIOS_DIR1=/home/sensei/sensei_insitu/software/adios/1.13.1/")
set(CTEST_BUILD_CONFIGURATION Debug)
set(CTEST_GIT_COMMAND "/usr/bin/git")
set(CTEST_TEST_ARGS PARALLEL_LEVEL 1)
set(CTEST_BUILD_FLAGS -j4)
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(DASHBOARD_RELIABLE FALSE)
#set(ALWAYS_UPDATE ON)
#set(INCREMENTAL_BUILD OFF)
include("${CTEST_DASHBOARD_ROOT}/sensei-dashboard.cmake")
