set(SENSEI_BACKEND $ENV{SENSEI_BACKEND})
set(SENSEI_BRANCH $ENV{SENSEI_BRANCH})
set(CTEST_SITE "sensei-ascent-sc19.dhcp.lbl.gov")
set(CTEST_BUILD_NAME "sensei-${SENSEI_BACKEND}-${SENSEI_BRANCH}")
set(CTEST_DASHBOARD_ROOT "$ENV{DASHROOT}")
# ascent specific
set(PREFIX_BASE /home/in-situ-user/sensei_insitu/software)
set(CONDUIT_DIR ${PREFIX_BASE}/conduit/2019-11-12)
set(VTKM_DIR ${PREFIX_BASE}/vtk-m/2019-11-12)
set(VTKH_DIR ${PREFIX_BASE}/vtk-h/2019-11-12)
set(BLT_DIR ${PREFIX_BASE}/blt/2019-11-12)
set(ASCENT_DIR ${PREFIX_BASE}/ascent/2019-11-12)
#
set(INITIAL_CACHE
"CMAKE_BUILD_TYPE=Debug
BUILD_TESTING=ON
ENABLE_SENSEI=ON
ENABLE_VTK_IO=ON
ENABLE_VTK_MPI=ON
ENABLE_PYTHON=ON
SENSEI_PYTHON_VERSION=3
ENABLE_ASCENT=ON
Ascent_DIR=${ASCENT_DIR}/lib/cmake
VTKH_DIR=${VTKH_DIR}
VTKM_DIR=${VTKM_DIR}
BLT_SOURCE_DIR=${BLT_DIR}
CONDUIT_DIR=${CONDUIT_DIR}
ENABLE_VTKM=OFF
ENABLE_HDF5=ON
HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi
ENABLE_ADIOS1=ON
ADIOS1_DIR=/home/sensei/sensei_insitu/software/adios/1.13.1/
VTK_DIR=/home/sensei/sensei_insitu/software/vtk/8.2.0/lib/cmake/vtk-8.2/")
set(CTEST_BUILD_CONFIGURATION Debug)
set(CTEST_GIT_COMMAND "/usr/bin/git")
set(CTEST_TEST_ARGS PARALLEL_LEVEL 1)
set(CTEST_BUILD_FLAGS -j4)
set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
set(DASHBOARD_RELIABLE FALSE)
set(ALWAYS_UPDATE ON)
set(INCREMENTAL_BUILD OFF)
include("${CTEST_DASHBOARD_ROOT}/sensei-dashboard.cmake")
